### ISSUE TITLE
Chrome pre-installed and set as default browser

### ISSUE THREAD

**Issue by zkniebel** [asmagin/sitecore-packer#10]
It would be great to have Chrome pre-installed and set as the default browser. This isn't a high-priority item, but it would help to save time and make browsing the web on the VM easier, when necessary.

**Comment by asmagin** [comment]
@zkniebel By design site should be available from the `host` machine and in most of the cases VM in running in headless mode. Default browser could be used for initial troublesooting, the rest could be done from host. 

Images have [chocolatey](https://chocolatey.org) preinstalled. Chrome can be easily installed as a part of provisioning of your VM via vagrant, see: https://www.vagrantup.com/docs/provisioning/shell.html

Add the following before the `end` in Vagrantfile, that you are using to spin up the machine.
``` ruby
  config.vm.provision "shell", inline: "choco install googlechrome -y"
```

To trigger proviosioning use `vagrant up --provision`
